version: 2
jobs:
  build:
    working_directory: ~/netGraph.svg
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: prepare
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: out
